export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const CLEAR_CART = "CLEAR_CART"
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART"

export const OPEN_LOGIN = "OPEN_LOGIN"
export const CLOSE_LOGIN = "CLOSE_LOGIN"
